<h2 style="margin: 24px 0 16px; font-size: 20px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 6px;">📘 Kontrola kvality dát a spracovanie chýb</h2>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">
V tejto úlohe budete pracovať so súborom
<span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">sales_data_dirty.csv</span>, ktorý zámerne obsahuje problémy
typické pre dáta získané z externého zdroja.
</p>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">
Vašou úlohou nebude iba „opraviť CSV“, ale navrhnúť postup, ktorý by bolo možné
neskôr použiť ako súčasť dátovej pipeline. Pri každom kroku preto odlišujte
<strong>detekciu problému</strong>, <strong>rozhodnutie o jeho spracovaní</strong>
a <strong>kontrolu výsledku</strong>.
</p>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">V datasete sa môžu nachádzať napríklad:</p>
<ul style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.7; margin-top: 6px;">
  <li>chýbajúce hodnoty,</li>
  <li>nekonzistentné kategórie,</li>
  <li>nesprávne dátové typy,</li>
  <li>neplatné alebo podozrivé číselné hodnoty,</li>
  <li>duplicitné identifikátory objednávok,</li>
  <li>rôzne formáty dátumov a neplatné dátumy,</li>
  <li>nekonzistentné telefónne čísla.</li>
</ul>
<div
  style="margin-top: 12px; background-color: #fff7ed; border-left: 4px solid #f59e0b; padding: 12px; border-radius: 4px;">
⚠️ <strong>Nezabudnite:</strong> Pri validácii dát neplatí, že každú chybu je správne
automaticky nahradiť nulou. Ak hodnotu nevieme spoľahlivo opraviť, je často lepšie
ju označiť ako neplatnú alebo záznam oddeliť na ďalšiu kontrolu.
</div>

<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Pri riešení pracujte s nasledujúcimi pravidlami:</p>
<ul style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.7; margin-top: 6px;">
  <li><span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">OrderID</span> musí existovať, mať formát <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">ORDdddd</span> a byť unikátny.</li>
  <li><span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">Region</span> musí po zjednotení obsahovať iba North, South, East alebo West.</li>
  <li><span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">Product</span> musí patriť do povolenej množiny produktov.</li>
  <li><span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">Quantity</span> musí byť kladné celé číslo.</li>
  <li><span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">SalesAmount</span> musí byť kladná číselná hodnota.</li>
  <li><span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">Discount</span> musí byť číslo v intervale 0 až 100.</li>
  <li><span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">OrderDate</span> a <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">DeliveryDate</span> musia byť platné dátumy a dodanie nesmie byť pred objednávkou.</li>
  <li><span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">PhoneNumber</span> je nepovinný, ale ak je vyplnený, po odstránení formátovacích znakov musí obsahovať 10 až 15 číslic.</li>
</ul>

<h2 style="margin: 24px 0 16px; font-size: 20px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 6px;">💻 Úloha 1 – Bezpečné načítanie vstupného súboru</h2>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Načítajte <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">sales_data_dirty.csv</span> tak, aby program vedel zrozumiteľne reagovať aj v prípade, že súbor neexistuje, je prázdny alebo sa ho nepodarí korektne parsovať.</p>
<ul style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.7; margin-top: 6px;">
<li>použite <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">try/except</span>,</li>
<li>po úspešnom načítaní vypíšte počet riadkov a stĺpcov, zobrazte prvých 5 riadkov.</li>
</ul>
<div
  style="margin-top: 12px; background-color: #f9fafb; border-left: 4px solid #60a5fa; padding: 12px; border-radius: 4px;">
  💡 <strong>Pomôcka:</strong> Pri čítaní súboru sa môže stať, že súbor neexistuje,
je prázdny alebo má poškodenú štruktúru. Takéto situácie je vhodné zachytiť pomocou
<span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">try/except</span>.
<br><br>
Príklad princípu:
<pre style="background: #f9fafb; padding: 14px; border-radius: 8px; overflow: auto; font-size: 14px; line-height: 1.5; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; margin: 10px 0 14px;">try:
    # operácia, ktorá môže zlyhať
except SomeError:
    # reakcia na konkrétny typ chyby</pre>
Pri CSV sa môžete stretnúť napríklad s <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">FileNotFoundError</span>,
<span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">EmptyDataError</span> alebo <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">ParserError</span>.
Vašou úlohou je vybrať vhodné výnimky a zobraziť zmysluplnú informáciu o tom, čo zlyhalo.
</div>

In [ ]:
import pandas as pd
from io import StringIO

INPUT_FILE = "sales_data_dirty.csv"


def load_csv(source, **read_kwargs):
    name = source if isinstance(source, str) else "vstup"
    try:
        data = pd.read_csv(source, **read_kwargs)
    except FileNotFoundError:
        print(f"CHYBA: súbor '{name}' neexistuje skontrolujte názov a priečinok.")
        raise
    except pd.errors.EmptyDataError:
        print(f"CHYBA: súbor '{name}' je prázdny nie je čo spracovať.")
        raise
    except pd.errors.ParserError as e:
        print(f"CHYBA: súbor '{name}' má poškodenú štruktúru a nedá sa parsovať: {e}")
        raise
    except UnicodeDecodeError as e:
        print(f"CHYBA: súbor '{name}' má neočakávané kódovanie: {e}")
        raise
    return data

test_inputs = {
    "neexistujúci súbor": "neexistuje.csv",
    "prázdny súbor": StringIO(""),
    "poškodená štruktúra": StringIO("a,b\n1,2\n3,4,5,6\n"),
}
for description, test_input in test_inputs.items():
    print(f"Test {description}:")
    try:
        load_csv(test_input)
    except (FileNotFoundError, pd.errors.EmptyDataError, pd.errors.ParserError):
        print("  -> chyba zachytená, pipeline by sa tu zastavila\n")

df = load_csv(INPUT_FILE, dtype=str)

print(f"Súbor '{INPUT_FILE}' bol úspešne načítaný.")
print("Počet riadkov:", df.shape[0])
print("Počet stĺpcov:", df.shape[1])
display(df.head())

Test – neexistujúci súbor:
CHYBA: súbor 'neexistuje.csv' neexistuje – skontrolujte názov a priečinok.
  -> chyba zachytená, pipeline by sa tu zastavila

Test – prázdny súbor:
CHYBA: súbor 'vstup' je prázdny – nie je čo spracovať.
  -> chyba zachytená, pipeline by sa tu zastavila

Test – poškodená štruktúra:
CHYBA: súbor 'vstup' má poškodenú štruktúru a nedá sa parsovať: Error tokenizing data. C error: Expected 2 fields in line 3, saw 4

  -> chyba zachytená, pipeline by sa tu zastavila

Súbor 'sales_data_dirty.csv' bol úspešne načítaný.
Počet riadkov: 200
Počet stĺpcov: 10

,OrderID,CustomerName,Region,Product,Quantity,SalesAmount,Discount,OrderDate,DeliveryDate,PhoneNumber
0,ORD1095,Bob Smith,South,Unknown,-1,2710.16,15,2025-04-06,2024-02-30,+2348012345678
1,ORD1015,Charlie Lee,West,phone,7,840USD,20,2025-01-16,2025-01-19,12345
2,ORD1030,Alice Johnson,West,phone,6,1805.15,15,2025-01-31,2025-02-01,555-018X
3,ORD1158,Ibrahim Musa,North,phone,0,NaN,5,2025-06-08,2025-06-21,+1-202-555-0178
4,ORD1128,Bob Smith,SOUTH,Laptop,9,3083.23,5,2025-05-09,2025-05-11,NaN

<h2 style="margin: 24px 0 16px; font-size: 20px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 6px;">💻 Úloha 2 – Základný audit datasetu</h2>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Skôr než začnete hodnoty opravovať, vytvorte si prehľad o tom, čo sa v súbore nachádza.</p>
<ul style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.7; margin-top: 6px;">
<li>zobrazte názvy stĺpcov a dátové typy, použite <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">info()</span> a <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">describe(include='all')</span>,</li>
<li>spočítajte chýbajúce hodnoty v jednotlivých stĺpcoch, zistite počet unikátnych hodnôt v kategóriách <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">Region</span> a <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">Product</span>.</li>
</ul>
<div
  style="margin-top: 12px; background-color: #f9fafb; border-left: 4px solid #60a5fa; padding: 12px; border-radius: 4px;">
  💡 <strong>Pomôcka:</strong> Audit znamená, že si dataset najprv „zmapujete“.
Zaujíma vás napríklad počet riadkov, názvy stĺpcov, dátové typy, počet chýbajúcich hodnôt
a nečakané kategórie.
<br><br>
Užitočné príkazy:
<pre style="background: #f9fafb; padding: 14px; border-radius: 8px; overflow: auto; font-size: 14px; line-height: 1.5; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; margin: 10px 0 14px;">df.info()
df.describe(include="all")
df.isna().sum()
df["column"].value_counts(dropna=False)</pre>
Cieľom tejto úlohy ešte nie je nič opravovať. Najprv si vytvorte obraz o tom, aké problémy v dátach vôbec máte.
</div>

In [5]:
print("Názvy stĺpcov:")
print(list(df.columns))

print("\nŠtruktúra a dátové typy:")
df.info()

print("\nPrehľad všetkých stĺpcov describe(include='all'):")
display(df.describe(include="all"))

print("Chýbajúce hodnoty v jednotlivých stĺpcoch:")
print(df.isna().sum())

for col in ["Region", "Product"]:
    counts = df[col].value_counts(dropna=False) 
    counts.index = counts.index.map(repr)  
    print(f"\n{col} počet unikátnych hodnôt: {df[col].nunique(dropna=False)}")
    print(counts.to_string())

Názvy stĺpcov:
['OrderID', 'CustomerName', 'Region', 'Product', 'Quantity', 'SalesAmount', 'Discount', 'OrderDate', 'DeliveryDate', 'PhoneNumber', 'OrderDate_clean', 'DeliveryDate_clean']

Štruktúra a dátové typy:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   OrderID             200 non-null    object
 1   CustomerName        178 non-null    object
 2   Region              200 non-null    object
 3   Product             200 non-null    object
 4   Quantity            200 non-null    object
 5   SalesAmount         194 non-null    object
 6   Discount            188 non-null    object
 7   OrderDate           200 non-null    object
 8   DeliveryDate        199 non-null    object
 9   PhoneNumber         162 non-null    object
 10  OrderDate_clean     197 non-null    datetime64[ns]
 11  DeliveryDate_clean  190 non-null    datetime64[ns]
dtypes: datetime64[ns](2), object(10)
memory usage: 18.9+ KB

Prehľad všetkých stĺpcov describe(include='all'):

,OrderID,CustomerName,Region,Product,Quantity,SalesAmount,Discount,OrderDate,DeliveryDate,PhoneNumber,OrderDate_clean,DeliveryDate_clean
count,200,178,200,200,200,194,188,200,199,162,197,190
unique,188,20,8,7,17,180,11,194,131,8,NaN,NaN
top,ORD1025,Ibrahim Musa,West,lap top,8,one hundred,30,15-01-2025,12/31/24,+44 20 7946 0958,NaN,NaN
freq,3,14,35,35,22,10,28,6,6,25,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-04-06 23:23:27.106598912,2025-04-10 15:17:03.157894656
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-01-01 00:00:00,2024-12-31 00:00:00
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-02-14 00:00:00,2025-02-17 00:00:00
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-04-06 00:00:00,2025-04-12 00:00:00
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-05-27 00:00:00,2025-06-05 18:00:00
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-07-19 00:00:00,2025-07-27 00:00:00

Chýbajúce hodnoty v jednotlivých stĺpcoch:
OrderID                0
CustomerName          22
Region                 0
Product                0
Quantity               0
SalesAmount            6
Discount              12
OrderDate              0
DeliveryDate           1
PhoneNumber           38
OrderDate_clean        3
DeliveryDate_clean    10
dtype: int64

Region počet unikátnych hodnôt: 8
Region
'West'      35
'South'     29
'North'     27
'north'     23
'East'      23
'Nrth'      23
'SOUTH '    21
'Souht'     19

Product počet unikátnych hodnôt: 7
Product
'lap top'      35
'Accessory'    32
'Unknown'      31
'phone '       30
'Tablet'       27
'Phone'        24
'Laptop'       21

**Zistenia z auditu** (zatiaľ nič neopravujeme, iba mapujeme problémy):

- všetky stĺpce sú text – čísla aj dátumy bude treba konvertovať,
- chýbajúce hodnoty: `CustomerName` 22, `SalesAmount` 6, `Discount` 12, `DeliveryDate` 1, `PhoneNumber` 38,
- `OrderID` má 200 riadkov, ale iba 188 unikátnych hodnôt → duplicity,
- `Region` má 8 variantov namiesto 4 (`north`, `Nrth`, `'SOUTH '` s medzerou, `Souht`),
- `Product` má 7 variantov (`lap top`, `'phone '` s medzerou, `Phone`, `Laptop`…),
- `SalesAmount` obsahuje menu a text (`840USD`, `$1,165`, `one hundred`, `??`), `Quantity` a `Discount` slová (`five`, `ten`),
- dátumy sú vo viacerých formátoch (`15-01-2025`, `03/24/2025`, `12/31/24`) a niektoré neexistujú (`2025-13-40`, `2024-02-30`).

<h2 style="margin: 24px 0 16px; font-size: 20px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 6px;">💻 Úloha 3 – Kontrola schémy a povinných stĺpcov</h2>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Pred ďalším spracovaním overte, či vstup obsahuje všetky stĺpce, ktoré pipeline očakáva. Ak niektorý chýba, spracovanie má skončiť s jasnou chybovou hláškou.</p>
<ul style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.7; margin-top: 6px;">
<li>vytvorte zoznam očakávaných stĺpcov, porovnajte ho so skutočnými stĺpcami datasetu, pri chýbajúcom stĺpci vyvolajte výnimku.</li>
</ul>
<div
  style="margin-top: 12px; background-color: #f9fafb; border-left: 4px solid #60a5fa; padding: 12px; border-radius: 4px;">
  💡 <strong>Pomôcka:</strong> Pipeline často očakáva presnú schému. Môžete si preto vytvoriť
zoznam povinných názvov stĺpcov a porovnať ho s <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">df.columns</span>.
<br><br>
Princíp:
<pre style="background: #f9fafb; padding: 14px; border-radius: 8px; overflow: auto; font-size: 14px; line-height: 1.5; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; margin: 10px 0 14px;">required = ["id", "date", "amount"]
# zistite, ktoré z required chýbajú v df.columns</pre>
Ak kritický stĺpec chýba, je vhodnejšie spracovanie zastaviť pomocou
<span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">raise ValueError(...)</span> než pokračovať s neúplnými dátami.
</div>

In [6]:
REQUIRED_COLUMNS = [
    "OrderID", "CustomerName", "Region", "Product", "Quantity",
    "SalesAmount", "Discount", "OrderDate", "DeliveryDate", "PhoneNumber",
]


def check_schema(data, required_columns):
    missing = [col for col in required_columns if col not in data.columns]
    unexpected = [col for col in data.columns if col not in required_columns]

    if missing:
        raise ValueError(f"Vo vstupe chýbajú povinné stĺpce: {missing}. Spracovanie sa zastavuje.")
    if unexpected:
        print(f"Upozornenie: neočakávané stĺpce {unexpected} nebudú spracované.")
    print("Kontrola schémy prešla všetky povinné stĺpce sú prítomné.")


check_schema(df, REQUIRED_COLUMNS)

try:
    check_schema(df.drop(columns=["SalesAmount"]), REQUIRED_COLUMNS)
except ValueError as e:
    print("\nTest bez stĺpca SalesAmount zachytená chyba:")
    print(e)

Upozornenie: neočakávané stĺpce ['OrderDate_clean', 'DeliveryDate_clean'] nebudú spracované.
Kontrola schémy prešla všetky povinné stĺpce sú prítomné.

Test bez stĺpca SalesAmount zachytená chyba:
Vo vstupe chýbajú povinné stĺpce: ['SalesAmount']. Spracovanie sa zastavuje.

<h2 style="margin: 24px 0 16px; font-size: 20px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 6px;">💻 Úloha 4 – Validácia identifikátora objednávky</h2>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Stĺpec <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">OrderID</span> je kľúčový identifikátor záznamu. Overte jeho formát a unikátnosť.</p>
<ul style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.7; margin-top: 6px;">
<li>nájdite hodnoty, ktoré nezodpovedajú formátu <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">ORD</span> + 4 číslice,</li>
<li>nájdite všetky riadky, ktorých <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">OrderID</span> sa vyskytuje viac než raz,</li>
<li>duplicitné riadky zatiaľ nemažte, iba ich oddeľte na kontrolu.</li>
</ul>
<div
  style="margin-top: 12px; background-color: #f9fafb; border-left: 4px solid #60a5fa; padding: 12px; border-radius: 4px;">
  💡 <strong>Pomôcka:</strong> Identifikátor má dve samostatné požiadavky:
<strong>správny formát</strong> a <strong>unikátnosť</strong>.
<br><br>
Na formát sa hodí:
<pre style="background: #f9fafb; padding: 14px; border-radius: 8px; overflow: auto; font-size: 14px; line-height: 1.5; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; margin: 10px 0 14px;">series.str.match(r"^ABC\d{3}$", na=False)</pre>
Toto je iba príklad iného formátu. Pre vaše <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">OrderID</span> si zostavte vlastný regex.
<br><br>
Na duplicity sa hodí:
<pre style="background: #f9fafb; padding: 14px; border-radius: 8px; overflow: auto; font-size: 14px; line-height: 1.5; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; margin: 10px 0 14px;">df.duplicated("id", keep=False)</pre>
Najprv si duplicitné riadky zobrazte. Neodstraňujte ich automaticky.
</div>

In [7]:
ORDER_ID_PATTERN = r"^ORD\d{4}$"  

invalid_order_id = ~df["OrderID"].str.match(ORDER_ID_PATTERN, na=False)
print("OrderID v nesprávnom formáte alebo chýbajúce:", invalid_order_id.sum())
if invalid_order_id.any():
    display(df.loc[invalid_order_id, ["OrderID"]])

duplicate_order_id = df.duplicated("OrderID", keep=False)
print("Riadky s duplicitným OrderID:", duplicate_order_id.sum())
print("Počet OrderID, ktoré sa opakujú:", df.loc[duplicate_order_id, "OrderID"].nunique())
print("Úplne zhodné riadky (vo všetkých stĺpcoch):", df.duplicated(keep=False).sum())

duplicates_for_review = df[duplicate_order_id].sort_values("OrderID", kind="stable")
display(duplicates_for_review)

OrderID v nesprávnom formáte alebo chýbajúce: 0
Riadky s duplicitným OrderID: 22
Počet OrderID, ktoré sa opakujú: 10
Úplne zhodné riadky (vo všetkých stĺpcoch): 0

,OrderID,CustomerName,Region,Product,Quantity,SalesAmount,Discount,OrderDate,DeliveryDate,PhoneNumber,OrderDate_clean,DeliveryDate_clean
90,ORD1022,George Miller,Souht,Unknown,8,2714.26,0,2025-01-23,2025-01-27,(202) 555-0189,2025-01-23,2025-01-27
108,ORD1022,Ibrahim Musa,SOUTH,Unknown,2,4152.49,20,2025-04-23,2025-04-25,+44 20 7946 0958,2025-04-23,2025-04-25
124,ORD1025,Nina Roberts,Nrth,Laptop,1,470.09,30,2025-01-26,2025-01-30,+1-202-555-0178,2025-01-26,2025-01-30
152,ORD1025,Ibrahim Musa,SOUTH,Tablet,7,3253.21,30,2025-03-31,2025-04-05,+1-202-555-0178,2025-03-31,2025-04-05
178,ORD1025,Alice Johnson,north,Phone,8,4287USD,10,2025-06-07,2025-06-20,(202) 555-0189,2025-06-07,2025-06-20
62,ORD1031,Fatima Yusuf,SOUTH,Tablet,7,1236.1,15,2025-02-01,12/31/24,12345,2025-02-01,2024-12-31
174,ORD1031,Fatima Yusuf,South,Unknown,2,535.93,25,06/10/2025,2025-06-21,NaN,2025-06-10,2025-06-21
32,ORD1035,Tina Zhang,SOUTH,Laptop,6,NaN,150,2025-02-25,2025-03-11,+44 20 7946 0958,2025-02-25,2025-03-11
64,ORD1035,Ella Brown,South,Laptop,6,2498.38,15,2025-02-05,2025-02-15,NaN,2025-02-05,2025-02-15
126,ORD1035,Hannah Davis,Souht,Unknown,5,2082.64,10,2025-07-04,2025-07-16,2025550185,2025-07-04,2025-07-16
75,ORD1080,Ella Brown,Souht,lap top,1,2940.19,15,2025-04-24,2025-05-04,+2348012345678,2025-04-24,2025-05-04
144,ORD1080,Charlie Lee,East,lap top,-1,1337.0,5,2025-03-22,12/31/24,+2348012345678,2025-03-22,2024-12-31
57,ORD1098,Kevin Patel,South,Accessory,0,4171.79,30,2025-04-09,2025-04-23,+44 20 7946 0958,2025-04-09,2025-04-23
137,ORD1098,George Miller,West,phone,8,321.54,30,04/16/2025,2025-04-29,2025550185,2025-04-16,2025-04-29
104,ORD1109,NaN,north,lap top,1,4856.04,20,2025-04-20,2025-04-23,NaN,2025-04-20,2025-04-23
160,ORD1109,Tina Zhang,Souht,Tablet,5,1008USD,-5,2025/02/30,2025-13-40,+1-202-555-0178,NaT,NaT
34,ORD1150,NaN,North,phone,10,2381.85,NaN,2025-05-31,2025-06-02,(202) 555-0189,2025-05-31,2025-06-02
84,ORD1150,Ella Brown,North,Tablet,2,7696USD,-5,2025-07-11,2025-07-25,08012345678,2025-07-11,2025-07-25
14,ORD1186,Charlie Lee,West,Phone,8,572.23,10,15-01-2025,2025-01-14,2025550185,2025-01-15,2025-01-14
42,ORD1186,David King,north,Phone,4,4496.56,30,2025-02-08,2025-02-15,12345,2025-02-08,2025-02-15
165,ORD1192,NaN,Nrth,Accessory,10,"$4,167",10,2025-02-24,2025-03-07,+1-202-555-0178,2025-02-24,2025-03-07
175,ORD1192,Ella Brown,SOUTH,phone,7,"$1,461",NaN,2025-07-12,2025-07-23,(202) 555-0189,2025-07-12,2025-07-23

**Rozhodnutie:** záznamy s rovnakým `OrderID` majú rôzny obsah (iný zákazník, produkt, suma), nejde teda o omylom zopakovaný riadok, ale o konflikt identifikátora. Nevieme určiť, ktorý záznam je správny, preto žiadny nemažeme ani neponechávame „prvý“. Všetky výskyty pôjdu na kontrolu (v úlohe 10 je duplicita kritické pravidlo).

<h2 style="margin: 24px 0 16px; font-size: 20px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 6px;">💻 Úloha 5 – Zjednotenie kategórií</h2>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Skontrolujte stĺpce <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">Region</span> a <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">Product</span>. Hodnoty, ktoré významovo označujú to isté, zjednoťte do jedného tvaru.</p>
<ul style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.7; margin-top: 6px;">
<li>odstráňte nadbytočné medzery, zjednoťte veľkosť písmen, opravte zjavné preklepy, po transformácii overte, že zostali iba povolené kategórie.</li>
</ul>
<div
  style="margin-top: 12px; background-color: #f9fafb; border-left: 4px solid #60a5fa; padding: 12px; border-radius: 4px;">
  💡 <strong>Pomôcka:</strong> Pri kategóriách je vhodné oddeliť
<strong>normalizáciu</strong> od <strong>opravy významu</strong>.
<br><br>
Normalizácia môže vyzerať napríklad:
<pre style="background: #f9fafb; padding: 14px; border-radius: 8px; overflow: auto; font-size: 14px; line-height: 1.5; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; margin: 10px 0 14px;">series.str.strip().str.lower()</pre>
Potom si môžete pripraviť slovník variantov:
<pre style="background: #f9fafb; padding: 14px; border-radius: 8px; overflow: auto; font-size: 14px; line-height: 1.5; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; margin: 10px 0 14px;">mapping = {
    "n": "North",
    "north ": "North"
}</pre>
Pri hodnote, ktorej význam si neviete jednoznačne odvodiť, ju radšej označte ako problém namiesto toho, aby ste ju „uhádli“.
</div>

In [8]:
ALLOWED_REGIONS = ["North", "South", "East", "West"]
ALLOWED_PRODUCTS = ["Laptop", "Phone", "Tablet", "Accessory", "Unknown"]


def normalize_text(series):
    """Normalizácia tvaru: okrajové medzery preč, viac medzier -> jedna, malé písmená."""
    return series.str.strip().str.replace(r"\s+", " ", regex=True).str.lower()


REGION_MAPPING = {
    "north": "North", "nrth": "North",
    "south": "South", "souht": "South",
    "east": "East",
    "west": "West",
}
PRODUCT_MAPPING = {
    "laptop": "Laptop", "lap top": "Laptop",
    "phone": "Phone",
    "tablet": "Tablet",
    "accessory": "Accessory",
    "unknown": "Unknown",
}

df["Region_clean"] = normalize_text(df["Region"]).map(REGION_MAPPING)
df["Product_clean"] = normalize_text(df["Product"]).map(PRODUCT_MAPPING)

print("Prevod Region (pôvodná hodnota -> zjednotená):")
print(df.groupby([df["Region"].map(repr), "Region_clean"], dropna=False).size().to_string())
print("\nPrevod Product (pôvodná hodnota -> zjednotená):")
print(df.groupby([df["Product"].map(repr), "Product_clean"], dropna=False).size().to_string())

invalid_region = ~df["Region_clean"].isin(ALLOWED_REGIONS)
invalid_product = ~df["Product_clean"].isin(ALLOWED_PRODUCTS)
print("\nNeplatné regióny po zjednotení:", invalid_region.sum())
print("Neplatné produkty po zjednotení:", invalid_product.sum())
print("Regióny po zjednotení:", sorted(df["Region_clean"].dropna().unique()))
print("Produkty po zjednotení:", sorted(df["Product_clean"].dropna().unique()))

Prevod Region (pôvodná hodnota -> zjednotená):
Region    Region_clean
'East'    East            23
'North'   North           27
'Nrth'    North           23
'SOUTH '  South           21
'Souht'   South           19
'South'   South           29
'West'    West            35
'north'   North           23

Prevod Product (pôvodná hodnota -> zjednotená):
Product      Product_clean
'Accessory'  Accessory        32
'Laptop'     Laptop           21
'Phone'      Phone            24
'Tablet'     Tablet           27
'Unknown'    Unknown          31
'lap top'    Laptop           35
'phone '     Phone            30

Neplatné regióny po zjednotení: 0
Neplatné produkty po zjednotení: 0
Regióny po zjednotení: ['East', 'North', 'South', 'West']
Produkty po zjednotení: ['Accessory', 'Laptop', 'Phone', 'Tablet', 'Unknown']

<h2 style="margin: 24px 0 16px; font-size: 20px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 6px;">💻 Úloha 6 – Číselné hodnoty a konverzné chyby</h2>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Stĺpce <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">Quantity</span>, <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">SalesAmount</span> a <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">Discount</span> obsahujú hodnoty, ktoré nie sú uložené konzistentne.</p>
<ul style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.7; margin-top: 6px;">
<li>identifikujte hodnoty, ktoré sa nedajú priamo skonvertovať na číslo, odstráňte formátovacie znaky, pri ktorých je význam jednoznačný (napr. mena alebo oddeľovač tisícov), konverziu vykonajte s <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">errors='coerce'</span> a následne odlíšte pôvodne chýbajúce hodnoty od hodnôt, ktoré sa stali <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">NaN</span> kvôli chybe konverzie,</li>
<li>overte business pravidlá pre rozsah hodnôt.</li>
</ul>
<div
  style="margin-top: 12px; background-color: #f9fafb; border-left: 4px solid #60a5fa; padding: 12px; border-radius: 4px;">
  💡 <strong>Pomôcka:</strong> Číselný stĺpec môže obsahovať napríklad medzery,
symbol meny alebo textové hodnoty. Najprv odstráňte iba tie znaky, pri ktorých je význam jasný.
<br><br>
Príklad:
<pre style="background: #f9fafb; padding: 14px; border-radius: 8px; overflow: auto; font-size: 14px; line-height: 1.5; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; margin: 10px 0 14px;">cleaned = series.str.replace("$", "", regex=False)
numeric = pd.to_numeric(cleaned, errors="coerce")</pre>
Po konverzii hľadajte <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">NaN</span> a následne overte business pravidlá,
napríklad kladnosť alebo povolený interval.
<br><br>
Pozor: <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">NaN</span> po konverzii môže znamenať niečo iné než pôvodne chýbajúca hodnota.
</div>

In [10]:
NUMERIC_COLUMNS = ["Quantity", "SalesAmount", "Discount"]

for col in NUMERIC_COLUMNS:
    direct = pd.to_numeric(df[col], errors="coerce")
    not_convertible = df[col].notna() & direct.isna()
    print(f"{col} priamo neskonvertovateľné hodnoty ({not_convertible.sum()}):")
    print("  ", sorted(df.loc[not_convertible, col].unique()))

TEXT_NUMBERS = {"one hundred": "100", "ten": "10", "five": "5"}  


def clean_numeric_text(series):
    s = series.str.strip().str.lower()
    s = s.replace(TEXT_NUMBERS)               
    s = s.str.replace("usd", "", regex=False)    
    s = s.str.replace("$", "", regex=False)      
    s = s.str.replace(",", "", regex=False)    
    return s.str.strip()


originally_missing = {}
conversion_error = {}
for col in NUMERIC_COLUMNS:
    df[f"{col}_clean"] = pd.to_numeric(clean_numeric_text(df[col]), errors="coerce")
    originally_missing[col] = df[col].isna()                                   
    conversion_error[col] = df[f"{col}_clean"].isna() & ~originally_missing[col]   

q = df["Quantity_clean"]
invalid_quantity = ~(q.notna() & (q > 0) & (q % 1 == 0))         
invalid_sales_amount = ~(df["SalesAmount_clean"] > 0)           
invalid_discount = ~df["Discount_clean"].between(0, 100)        

invalid_numeric = {
    "Quantity": invalid_quantity,
    "SalesAmount": invalid_sales_amount,
    "Discount": invalid_discount,
}
numeric_summary = pd.DataFrame({
    "pôvodne chýbajúce": {c: originally_missing[c].sum() for c in NUMERIC_COLUMNS},
    "chyba konverzie": {c: conversion_error[c].sum() for c in NUMERIC_COLUMNS},
    "mimo povoleného rozsahu": {
        c: (invalid_numeric[c] & df[f"{c}_clean"].notna()).sum() for c in NUMERIC_COLUMNS
    },
    "spolu neplatné": {c: invalid_numeric[c].sum() for c in NUMERIC_COLUMNS},
})
print("\nPrehľad po konverzii:")
display(numeric_summary)

for col in NUMERIC_COLUMNS:
    errors = df.loc[conversion_error[col], col]
    if len(errors):
        print(f"{col} hodnoty, ktoré sa nepodarilo skonvertovať:", errors.value_counts().to_dict())
    out_of_range = df.loc[invalid_numeric[col] & df[f"{col}_clean"].notna(), f"{col}_clean"]
    print(f"{col} hodnoty mimo pravidla:", out_of_range.value_counts().sort_index().to_dict())

Quantity priamo neskonvertovateľné hodnoty (5):
   ['five', 'ten']
SalesAmount priamo neskonvertovateľné hodnoty (48):
   ['$1,143', '$1,165', '$1,325', '$1,339', '$1,461', '$186', '$2,192', '$2,952', '$2,987', '$3,267', '$3,410', '$4,167', '$4,545', '$4,609', '$4,868', '$567', '1008USD', '2464USD', '3347USD', '3736USD', '4287USD', '5448USD', '6002USD', '6305USD', '7627USD', '7696USD', '7891USD', '8259USD', '840USD', '8488USD', '9677USD', '9877USD', '??', 'one hundred']
Discount priamo neskonvertovateľné hodnoty (9):
   ['ten']

Prehľad po konverzii:

,pôvodne chýbajúce,chyba konverzie,mimo povoleného rozsahu,spolu neplatné
Quantity,0,0,24,24
SalesAmount,6,6,0,12
Discount,12,0,8,20

Quantity hodnoty mimo pravidla: {-1.0: 10, 0.0: 9, 3.5: 5}
SalesAmount hodnoty, ktoré sa nepodarilo skonvertovať: {'??': 6}
SalesAmount hodnoty mimo pravidla: {}
Discount hodnoty mimo pravidla: {-5.0: 4, 150.0: 4}

**Rozhodnutia pri číslach:**

- `$`, `USD` a čiarku (oddeľovač tisícov) odstraňujeme – význam je jednoznačný.
- Slová `one hundred`, `ten`, `five` prevádzame cez explicitný slovník – ide o jednoznačne zapísané číslo, nie o odhad.
- `??` sa opraviť nedá → zostane `NaN` a je označené ako chyba konverzie. **Nenahrádzame ho nulou**, nula by bola vymyslená hodnota.
- Pôvodne chýbajúcu hodnotu a chybu konverzie počítame zvlášť: prvá znamená „zdroj hodnotu neposlal“, druhá „zdroj poslal nezmysel“.
- `Quantity` 3.5, 0 a -1 sú síce čísla, ale porušujú pravidlo kladného celého čísla. Rovnako `Discount` -5 a 150.

<h2 style="margin: 24px 0 16px; font-size: 20px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 6px;">💻 Úloha 7 – Dátumy a logická konzistencia</h2>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Skonvertujte <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">OrderDate</span> a <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">DeliveryDate</span> na dátumový typ a skontrolujte nielen formát, ale aj vzájomnú logiku.</p>
<ul style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.7; margin-top: 6px;">
<li>neplatné dátumy preveďte na <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">NaT</span>,</li>
<li>nájdite záznamy, v ktorých sa dátum nepodarilo skonvertovať,nájdite objednávky, pri ktorých je <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">DeliveryDate</span> skorší než <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">OrderDate</span>.</li>
</ul>
<div
  style="margin-top: 12px; background-color: #f9fafb; border-left: 4px solid #60a5fa; padding: 12px; border-radius: 4px;">
  💡 <strong>Pomôcka:</strong> Prvý krok je bezpečná konverzia:
<pre style="background: #f9fafb; padding: 14px; border-radius: 8px; overflow: auto; font-size: 14px; line-height: 1.5; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; margin: 10px 0 14px;">pd.to_datetime(series, errors="coerce")</pre>
Neplatné hodnoty sa zmenia na <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">NaT</span>.
Potom však ešte musíte skontrolovať logiku medzi dvoma dátumami.
<br><br>
Príklad logickej kontroly:
<pre style="background: #f9fafb; padding: 14px; border-radius: 8px; overflow: auto; font-size: 14px; line-height: 1.5; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; margin: 10px 0 14px;">end_date < start_date</pre>
Takýto záznam môže obsahovať dva úplne platné dátumy, ale ich vzájomný vzťah je chybný.
</div>

In [11]:
DATE_FORMATS = [
    "%Y-%m-%d",   
    "%Y/%m/%d",  
    "%d-%m-%Y",  
    "%m/%d/%Y",   
    "%m/%d/%y",   
]


def parse_dates(series):
    s = series.str.strip()
    result = pd.to_datetime(s, format=DATE_FORMATS[0], errors="coerce")
    for fmt in DATE_FORMATS[1:]:
        result = result.fillna(pd.to_datetime(s, format=fmt, errors="coerce"))
    return result


df["OrderDate_clean"] = parse_dates(df["OrderDate"])
df["DeliveryDate_clean"] = parse_dates(df["DeliveryDate"])

invalid_order_date = df["OrderDate_clean"].isna()
invalid_delivery_date = df["DeliveryDate_clean"].isna()
print("Neplatný OrderDate:", invalid_order_date.sum())
print(
    "Neplatný alebo chýbajúci DeliveryDate:", invalid_delivery_date.sum(),
    f"(z toho chýbajúce vo vstupe: {df['DeliveryDate'].isna().sum()})",
)
date_cols = ["OrderID", "OrderDate", "DeliveryDate", "OrderDate_clean", "DeliveryDate_clean"]
display(df.loc[invalid_order_date | invalid_delivery_date, date_cols])

delivery_before_order = df["DeliveryDate_clean"] < df["OrderDate_clean"]
print("Dodanie pred objednávkou:", delivery_before_order.sum())
display(df.loc[delivery_before_order, date_cols])

Neplatný OrderDate: 3
Neplatný alebo chýbajúci DeliveryDate: 10 (z toho chýbajúce vo vstupe: 1)

     OrderID   OrderDate DeliveryDate OrderDate_clean DeliveryDate_clean
0    ORD1095  2025-04-06   2024-02-30      2025-04-06                NaT
13   ORD1078  2025-03-20   2024-02-30      2025-03-20                NaT
28   ORD1125  2025-05-06   2025-00-10      2025-05-06                NaT
59   ORD1096  2025-13-40   2025-13-40             NaT                NaT
69   ORD1136  2025-05-17   2025-00-10      2025-05-17                NaT
71   ORD1127  2025-05-08   2025-00-10      2025-05-08                NaT
118  ORD1163  2025/02/30          NaN             NaT                NaT
150  ORD1176  2025-06-26   2025-00-10      2025-06-26                NaT
160  ORD1109  2025/02/30   2025-13-40             NaT                NaT
196  ORD1014  2025-01-15   2025-00-10      2025-01-15                NaT

Dodanie pred objednávkou: 18

     OrderID   OrderDate DeliveryDate OrderDate_clean DeliveryDate_clean
11   ORD1182  2025-07-02     12/31/24      2025-07-02         2024-12-31
12   ORD1165  2025-06-15   2025-06-13      2025-06-15         2025-06-13
14   ORD1186  15-01-2025   2025-01-14      2025-01-15         2025-01-14
29   ORD1132  2025-05-13   2025-05-09      2025-05-13         2025-05-09
30   ORD1009  2025-01-10   2025-01-06      2025-01-10         2025-01-06
44   ORD1122  2025-05-03   2025-04-30      2025-05-03         2025-04-30
62   ORD1031  2025-02-01     12/31/24      2025-02-01         2024-12-31
63   ORD1012  2025-01-13   2025-01-09      2025-01-13         2025-01-09
68   ORD1090  2025-04-01   2025-03-28      2025-04-01         2025-03-28
70   ORD1051  02/21/2025   2025-02-19      2025-02-21         2025-02-19
85   ORD1085  03/27/2025     12/31/24      2025-03-27         2024-12-31
98   ORD1027  2025-01-28     12/31/24      2025-01-28         2024-12-31
101  ORD1032  2025-02-02   2025-01-29      2025-02-02         2025-01-29
129  ORD1039  2025-02-09   2025-02-04      2025-02-09         2025-02-04
132  ORD1094  2025-04-05   2025-04-01      2025-04-05         2025-04-01
144  ORD1080  2025-03-22     12/31/24      2025-03-22         2024-12-31
149  ORD1083  2025-03-25     12/31/24      2025-03-25         2024-12-31
154  ORD1013  2025-01-14   2025-01-13      2025-01-14         2025-01-13

**Prečo zoznam formátov a nie `format="mixed"`:** pri „mixed“ si pandas formát hádá pre každú hodnotu zvlášť, takže napríklad `06/10/2025` môže byť 6. októbra alebo 10. júna. Explicitný zoznam robí rozhodnutie viditeľným a pri každom behu pipeline rovnakým. Že sa v zdroji píše mesiac ako prvý, vidno z hodnôt ako `03/24/2025` (24 nemôže byť mesiac). Neexistujúce dátumy (`2025-13-40`, `2024-02-30`, `2025-00-10`) nesedia na žiadny formát, preto skončia ako `NaT`.

<h2 style="margin: 24px 0 16px; font-size: 20px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 6px;">💻 Úloha 8 – Validácia telefónneho čísla</h2>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Telefónne čísla sú v súbore zapísané v rôznych formátoch. Stĺpec je nepovinný, ale vyplnená hodnota musí byť validná.</p>
<ul style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.7; margin-top: 6px;">
<li>odstráňte medzery, zátvorky, pomlčky a znak <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">+</span>,</li>
<li>ponechajte iba číslice, za platné považujte hodnoty s 10 až 15 číslicami, neplatné, ale vyplnené telefónne čísla označte samostatným validačným príznakom.</li>
</ul>
<div
  style="margin-top: 12px; background-color: #f9fafb; border-left: 4px solid #60a5fa; padding: 12px; border-radius: 4px;">
  💡 <strong>Pomôcka:</strong> Telefónne čísla môžu mať rôzne formátovanie.
Najprv preto vytvorte pomocnú hodnotu, v ktorej zostanú iba číslice.
<pre style="background: #f9fafb; padding: 14px; border-radius: 8px; overflow: auto; font-size: 14px; line-height: 1.5; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; margin: 10px 0 14px;">digits = series.str.replace(r"\D", "", regex=True)</pre>
Potom môžete kontrolovať dĺžku pomocou <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">str.len()</span>.
<br><br>
Rozlišujte medzi <strong>chýbajúcou hodnotou</strong> a <strong>vyplnenou, ale neplatnou hodnotou</strong>.
Keď je telefón nepovinný, prázdna hodnota nemusí byť chyba.
</div>

In [12]:
phone_raw = df["PhoneNumber"]

phone_stripped = phone_raw.str.replace(r"[\s()\-+]", "", regex=True)
phone_is_valid = phone_stripped.str.fullmatch(r"\d{10,15}", na=False)

df["PhoneNumber_clean"] = phone_stripped.where(phone_is_valid)

phone_missing = phone_raw.isna()                     
invalid_phone = phone_raw.notna() & ~phone_is_valid   

print("Chýbajúce telefónne čísla (nepovinné, nie je to chyba):", phone_missing.sum())
print("Platné telefónne čísla:", phone_is_valid.sum())
print("Vyplnené, ale neplatné telefónne čísla:", invalid_phone.sum())

phone_overview = (
    pd.DataFrame({
        "pôvodná hodnota": phone_raw,
        "po odstránení znakov": phone_stripped,
        "počet znakov": phone_stripped.str.len().astype("Int64"),
        "platné": phone_is_valid,
    })
    .dropna(subset=["pôvodná hodnota"])
    .drop_duplicates("pôvodná hodnota")
    .sort_values("platné")
)
display(phone_overview)

Chýbajúce telefónne čísla (nepovinné, nie je to chyba): 38
Platné telefónne čísla: 128
Vyplnené, ale neplatné telefónne čísla: 34

     pôvodná hodnota po odstránení znakov  počet znakov  platné
1              12345                12345             5   False
2           555-018X              555018X             7   False
0     +2348012345678        2348012345678            13    True
3    +1-202-555-0178          12025550178            11    True
6     (202) 555-0189           2025550189            10    True
10       08012345678          08012345678            11    True
14        2025550185           2025550185            10    True
21  +44 20 7946 0958         442079460958            12    True

<h2 style="margin: 24px 0 16px; font-size: 20px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 6px;">💻 Úloha 9 – Vytvorenie validačného reportu</h2>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Namiesto toho, aby boli jednotlivé kontroly roztrúsené po notebooku, vytvorte jeden prehľad, ktorý ukáže počet nájdených problémov podľa typu.</p>
<ul style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.7; margin-top: 6px;">
<li>vytvorte validačné príznaky pre jednotlivé pravidlá, zostavte z nich tabuľku <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">validation_report</span>,</li>
<li>pri každom pravidle zobrazte počet chybných riadkov.</li>
</ul>
<div
  style="margin-top: 12px; background-color: #f9fafb; border-left: 4px solid #60a5fa; padding: 12px; border-radius: 4px;">
  💡 <strong>Pomôcka:</strong> Dobrá validačná pipeline si pri každom pravidle vytvorí boolean príznak:
<span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">True</span> = problém, <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">False</span> = v poriadku.
<br><br>
Napríklad všeobecne:
<pre style="background: #f9fafb; padding: 14px; border-radius: 8px; overflow: auto; font-size: 14px; line-height: 1.5; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; margin: 10px 0 14px;">flags["invalid_amount"] = ...
flags["invalid_date"] = ...</pre>
Keď máte pravidlá pokope, <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">sum()</span> vám dá počet chýb pre každý typ.
Takto získate report, ktorý sa dá neskôr logovať alebo monitorovať.
</div>

In [13]:
missing_customer = df["CustomerName"].isna()

flags = pd.DataFrame({
    "invalid_order_id": invalid_order_id,
    "duplicate_order_id": duplicate_order_id,
    "missing_customer": missing_customer,
    "invalid_region": invalid_region,
    "invalid_product": invalid_product,
    "invalid_quantity": invalid_quantity,
    "invalid_sales_amount": invalid_sales_amount,
    "invalid_discount": invalid_discount,
    "invalid_order_date": invalid_order_date,
    "invalid_delivery_date": invalid_delivery_date,
    "delivery_before_order": delivery_before_order,
    "invalid_phone": invalid_phone,
})

validation_report = (
    flags.sum()
    .rename_axis("validation_rule")
    .reset_index(name="invalid_rows")
    .sort_values("invalid_rows", ascending=False, kind="stable")
    .reset_index(drop=True)
)
validation_report["invalid_pct"] = (validation_report["invalid_rows"] / len(df) * 100).round(1)

display(validation_report)
print("Riadky bez jediného problému:", (~flags.any(axis=1)).sum(), "z", len(df))

          validation_rule  invalid_rows  invalid_pct
0           invalid_phone            34         17.0
1        invalid_quantity            24         12.0
2      duplicate_order_id            22         11.0
3        missing_customer            22         11.0
4        invalid_discount            20         10.0
5   delivery_before_order            18          9.0
6    invalid_sales_amount            12          6.0
7   invalid_delivery_date            10          5.0
8      invalid_order_date             3          1.5
9        invalid_order_id             0          0.0
10         invalid_region             0          0.0
11        invalid_product             0          0.0

Riadky bez jediného problému: 90 z 200

<h2 style="margin: 24px 0 16px; font-size: 20px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 6px;">💻 Úloha 10 – Oddelenie validných a problémových záznamov</h2>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Nie všetky chyby majú rovnakú závažnosť. Navrhnite, ktoré chyby považujete za kritické pre ďalšie spracovanie a ktoré môžu zostať iba ako upozornenie.</p>
<ul style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.7; margin-top: 6px;">
<li>vytvorte masku kritických chýb, rozdeľte dáta na <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">clean_data</span> a <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">rejected_records</span>,</li>
<li>pri zamietnutých záznamoch zachovajte informáciu o dôvode zamietnutia.</li>
</ul>
<div
  style="margin-top: 12px; background-color: #f9fafb; border-left: 4px solid #60a5fa; padding: 12px; border-radius: 4px;">
  💡 <strong>Pomôcka:</strong> Ak má každý validačný test vlastný boolean stĺpec,
môžete sa na úroveň celého riadku opýtať:
<em>porušil tento riadok aspoň jedno kritické pravidlo?</em>
<br><br>
Na to sa hodí:
<pre style="background: #f9fafb; padding: 14px; border-radius: 8px; overflow: auto; font-size: 14px; line-height: 1.5; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; margin: 10px 0 14px;">flags[critical_rules].any(axis=1)</pre>
Výsledkom je maska, ktorou môžete rozdeliť dáta na validné a problémové.
Pri problémových riadkoch je užitočné ponechať aj informáciu, ktoré pravidlá zlyhali.
</div>

In [14]:
CRITICAL_RULES = [
    "invalid_order_id",
    "duplicate_order_id",
    "invalid_region",
    "invalid_product",
    "invalid_quantity",
    "invalid_sales_amount",
    "invalid_discount",
    "invalid_order_date",
    "invalid_delivery_date",
    "delivery_before_order",
]
WARNING_RULES = [rule for rule in flags.columns if rule not in CRITICAL_RULES]

critical_mask = flags[CRITICAL_RULES].any(axis=1)


def list_failed_rules(flag_row):
    """Z riadku príznakov vráti názvy porušených pravidiel oddelené čiarkou."""
    return ", ".join(flag_row.index[flag_row.to_numpy()])


rejection_reason = flags[CRITICAL_RULES].apply(list_failed_rules, axis=1)
warning_reason = flags[WARNING_RULES].apply(list_failed_rules, axis=1)

clean_data = df[~critical_mask].copy()

rejected_records = df[critical_mask].copy()
rejected_records["rejection_reason"] = rejection_reason[critical_mask]   
rejected_records["warnings"] = warning_reason[critical_mask]                  

validation_report["severity"] = validation_report["validation_rule"].map(
    lambda rule: "critical" if rule in CRITICAL_RULES else "warning"
)

print("Vstupné riadky:", len(df))
print("Čisté riadky (clean_data):", len(clean_data))
print("Zamietnuté riadky (rejected_records):", len(rejected_records))
print("Upozornenie pravidlá:", WARNING_RULES)

print("\nKoľko zamietnutých riadkov porušilo jednotlivé kritické pravidlá:")
print(flags.loc[critical_mask, CRITICAL_RULES].sum().sort_values(ascending=False).to_string())

display(rejected_records[["OrderID", "rejection_reason", "warnings"]].head(10))

Vstupné riadky: 200
Čisté riadky (clean_data): 119
Zamietnuté riadky (rejected_records): 81
Upozornenie pravidlá: ['missing_customer', 'invalid_phone']

Koľko zamietnutých riadkov porušilo jednotlivé kritické pravidlá:
invalid_quantity         24
duplicate_order_id       22
invalid_discount         20
delivery_before_order    18
invalid_sales_amount     12
invalid_delivery_date    10
invalid_order_date        3
invalid_order_id          0
invalid_region            0
invalid_product           0

,OrderID,rejection_reason,warnings
0,ORD1095,"invalid_quantity, invalid_delivery_date",
3,ORD1158,"invalid_quantity, invalid_sales_amount",
5,ORD1115,invalid_quantity,
6,ORD1069,"invalid_quantity, invalid_discount",
9,ORD1045,invalid_sales_amount,invalid_phone
11,ORD1182,delivery_before_order,invalid_phone
12,ORD1165,delivery_before_order,missing_customer
13,ORD1078,"invalid_discount, invalid_delivery_date","missing_customer, invalid_phone"
14,ORD1186,"duplicate_order_id, delivery_before_order",
17,ORD1152,invalid_quantity,

**Rozdelenie pravidiel:**

| Závažnosť | Pravidlá | Prečo |
|---|---|---|
| kritické | `invalid_order_id`, `duplicate_order_id` | bez jednoznačného kľúča sa záznam nedá spoľahlivo identifikovať ani spájať s inými dátami |
| kritické | `invalid_region`, `invalid_product` | neznáma kategória by vypadla z agregácií alebo vytvorila falošnú skupinu |
| kritické | `invalid_quantity`, `invalid_sales_amount`, `invalid_discount` | neplatné alebo chýbajúce čísla by skreslili súčty a priemery |
| kritické | `invalid_order_date`, `invalid_delivery_date`, `delivery_before_order` | bez platných dátumov nefungujú časové analýzy ani výpočet doby doručenia |
| upozornenie | `missing_customer` | meno je iba popisný údaj, výpočty neovplyvní |
| upozornenie | `invalid_phone` | telefón je nepovinný, neplatné číslo sa iba nepoužije |

<h2 style="margin: 24px 0 16px; font-size: 20px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 6px;">💻 Úloha 11 – Finalizácia čistej schémy</h2>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">V dátach, ktoré prešli kritickou validáciou, nahraďte pôvodné nekonzistentné stĺpce vyčistenými verziami a ponechajte iba finálnu schému vhodnú na ďalšie spracovanie.</p>
<ul style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.7; margin-top: 6px;">
<li>nahraďte <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">Region</span>, <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">Product</span>, numerické a dátumové stĺpce vyčistenými hodnotami,</li>
<li>odstráňte pomocné stĺpce, nastavte vhodné dátové typy, znovu skontrolujte <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">info()</span> a chýbajúce hodnoty.</li>
</ul>
<div
  style="margin-top: 12px; background-color: #f9fafb; border-left: 4px solid #60a5fa; padding: 12px; border-radius: 4px;">
  💡 <strong>Pomôcka:</strong> Po čistení máte často pôvodné aj pomocné stĺpce,
napríklad <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">Region</span> a <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">Region_clean</span>.
Finálny dataset by mal obsahovať iba stabilnú schému, ktorú očakáva ďalší krok pipeline.
<br>
Môžete vytvoriť nový DataFrame výberom a premenovaním vyčistených stĺpcov.
Na konci znovu použite <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">info()</span> a
<span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">isna().sum()</span>.
</div>

In [15]:
clean_final = pd.DataFrame({
    "OrderID": clean_data["OrderID"],
    "CustomerName": clean_data["CustomerName"].str.strip().fillna("Unknown"),
    "Region": clean_data["Region_clean"],
    "Product": clean_data["Product_clean"],
    "Quantity": clean_data["Quantity_clean"],
    "SalesAmount": clean_data["SalesAmount_clean"],
    "Discount": clean_data["Discount_clean"],
    "OrderDate": clean_data["OrderDate_clean"],
    "DeliveryDate": clean_data["DeliveryDate_clean"],
    "PhoneNumber": clean_data["PhoneNumber_clean"],   # neplatné čísla sú už NaN
}).reset_index(drop=True)

clean_final = clean_final.astype({
    "OrderID": "string",
    "CustomerName": "string",
    "Region": pd.CategoricalDtype(ALLOWED_REGIONS),
    "Product": pd.CategoricalDtype(ALLOWED_PRODUCTS),
    "Quantity": "int64",
    "SalesAmount": "float64",
    "Discount": "float64",
    "PhoneNumber": "string",   
})

print("Finálna schéma vyčistených dát:")
clean_final.info()

print("\nChýbajúce hodnoty:")
print(clean_final.isna().sum())

display(clean_final.head())

Finálna schéma vyčistených dát:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119 entries, 0 to 118
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   OrderID       119 non-null    string
 1   CustomerName  119 non-null    string
 2   Region        119 non-null    category
 3   Product       119 non-null    category
 4   Quantity      119 non-null    int64
 5   SalesAmount   119 non-null    float64
 6   Discount      119 non-null    float64
 7   OrderDate     119 non-null    datetime64[ns]
 8   DeliveryDate  119 non-null    datetime64[ns]
 9   PhoneNumber   73 non-null     string
dtypes: category(2), datetime64[ns](2), float64(2), int64(1), string(3)
memory usage: 8.2 KB

Chýbajúce hodnoty:
OrderID          0
CustomerName     0
Region           0
Product          0
Quantity         0
SalesAmount      0
Discount         0
OrderDate        0
DeliveryDate     0
PhoneNumber     46
dtype: int64

,OrderID,CustomerName,Region,Product,Quantity,SalesAmount,Discount,OrderDate,DeliveryDate,PhoneNumber
0,ORD1015,Charlie Lee,West,Phone,7,840.00,20.0,2025-01-16,2025-01-19,<NA>
1,ORD1030,Alice Johnson,West,Phone,6,1805.15,15.0,2025-01-31,2025-02-01,<NA>
2,ORD1128,Bob Smith,South,Laptop,9,3083.23,5.0,2025-05-09,2025-05-11,<NA>
3,ORD1170,Lola Ade,North,Accessory,1,1380.89,10.0,2025-06-20,2025-06-22,<NA>
4,ORD1174,Alice Johnson,South,Unknown,9,3710.03,15.0,2025-06-24,2025-07-02,12025550178

Jediné chýbajúce hodnoty vo finálnych dátach sú v `PhoneNumber`. To je v poriadku: stĺpec je nepovinný a neplatné čísla sme zámerne nahradili prázdnou hodnotou, aby sa ďalej nepoužívali.

<h2 style="margin: 24px 0 16px; font-size: 20px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 6px;">💻 Úloha 12 – Opätovná validácia a error handling</h2>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Po čistení vykonajte validačné pravidlá ešte raz. Ak kritické chyby stále zostali, pipeline nemá pokračovať ako keby bolo všetko v poriadku.</p>
<ul style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.7; margin-top: 6px;">
<li>vytvorte vlastnú výnimku <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">DataValidationError</span> alebo použite vhodnú existujúcu výnimku,</li>
<li>overte unikátnosť <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">OrderID</span>,</li>
<li>overte rozsahy číselných hodnôt a logiku dátumov, pri zlyhaní vyvolajte výnimku s informatívnou správou.</li>
</ul>
<div
  style="margin-top: 12px; background-color: #f9fafb; border-left: 4px solid #60a5fa; padding: 12px; border-radius: 4px;">
  💡 <strong>Pomôcka:</strong> Po čistení je vhodné najdôležitejšie pravidlá spustiť ešte raz.
Ak kritická podmienka stále neplatí, spracovanie sa má zastaviť.
<br><br>
Vlastná výnimka môže mať tvar:
<pre style="background: #f9fafb; padding: 14px; border-radius: 8px; overflow: auto; font-size: 14px; line-height: 1.5; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; margin: 10px 0 14px;">class MyValidationError(Exception):
    pass</pre>
A pri zistení problému ju môžete vyvolať pomocou:
<pre style="background: #f9fafb; padding: 14px; border-radius: 8px; overflow: auto; font-size: 14px; line-height: 1.5; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; margin: 10px 0 14px;">raise MyValidationError("...")</pre>
Nejde o to vyhadzovať výnimku pri každom NULL-e. Výnimka je vhodná vtedy, keď ďalšie spracovanie už nie je bezpečné.
</div>

In [16]:
class DataValidationError(Exception):
    """Dáta nesplnili kritické pravidlá – ďalšie spracovanie nie je bezpečné."""


def validate_final_data(data):
    """Znovu overí kritické pravidlá. Pri porušení vyvolá DataValidationError."""
    problems = []

    if not data["OrderID"].is_unique:
        duplicated_ids = data.loc[data["OrderID"].duplicated(keep=False), "OrderID"].unique().tolist()
        problems.append(f"OrderID nie je unikátne: {duplicated_ids}")
    if not data["OrderID"].str.fullmatch(r"ORD\d{4}", na=False).all():
        problems.append("OrderID nemá formát ORDdddd")

    required = ["OrderID", "Region", "Product", "Quantity", "SalesAmount",
                "Discount", "OrderDate", "DeliveryDate"]
    missing = data[required].isna().sum()
    if missing.any():
        problems.append(f"chýbajúce hodnoty v povinných stĺpcoch: {missing[missing > 0].to_dict()}")

    if not data["Region"].isin(ALLOWED_REGIONS).all():
        problems.append("Region obsahuje nepovolenú hodnotu")
    if not data["Product"].isin(ALLOWED_PRODUCTS).all():
        problems.append("Product obsahuje nepovolenú hodnotu")

    bad_quantity = (data["Quantity"] <= 0) | (data["Quantity"] % 1 != 0)
    if bad_quantity.any():
        problems.append(f"Quantity nie je kladné celé číslo (počet riadkov: {bad_quantity.sum()})")
    if (data["SalesAmount"] <= 0).any():
        problems.append("SalesAmount musí byť kladné")
    if not data["Discount"].between(0, 100).all():
        problems.append("Discount je mimo intervalu 0 až 100")

    bad_dates = data["DeliveryDate"] < data["OrderDate"]
    if bad_dates.any():
        problems.append(f"DeliveryDate je pred OrderDate (počet riadkov: {bad_dates.sum()})")

    if not data["PhoneNumber"].dropna().str.fullmatch(r"\d{10,15}").all():
        problems.append("PhoneNumber obsahuje neplatné číslo")

    if problems:
        raise DataValidationError("Validácia vyčistených dát zlyhala:\n- " + "\n- ".join(problems))
    print(f"Záverečná validácia prešla: všetkých {len(data)} riadkov spĺňa kritické pravidlá.")


validate_final_data(clean_final)

# Overenie, že validácia naozaj zastaví pipeline – na kópii dát vyrobíme chyby
bad_row = clean_final.head(1).copy()                                    # rovnaké OrderID -> duplicita
bad_row["Quantity"] = -3                                                 # záporné množstvo
bad_row["DeliveryDate"] = bad_row["OrderDate"] - pd.Timedelta(days=5)    # dodanie pred objednávkou
broken = pd.concat([clean_final, bad_row], ignore_index=True)
try:
    validate_final_data(broken)
except DataValidationError as e:
    print("\nTest s úmyselne pokazenými dátami – zachytená DataValidationError:")
    print(e)

Záverečná validácia prešla: všetkých 119 riadkov spĺňa kritické pravidlá.

Test s úmyselne pokazenými dátami – zachytená DataValidationError:
Validácia vyčistených dát zlyhala:
- OrderID nie je unikátne: ['ORD1015']
- Quantity nie je kladné celé číslo (počet riadkov: 1)
- DeliveryDate je pred OrderDate (počet riadkov: 1)

<h2 style="margin: 24px 0 16px; font-size: 20px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 6px;">💻 Úloha 13 – Uloženie výsledkov validácie</h2>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Na konci vytvorte samostatné výstupy pre dáta, ktoré môžu pokračovať do ďalšieho spracovania, a pre záznamy, ktoré vyžadujú kontrolu.</p>
<ul style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.7; margin-top: 6px;">
<li>uložte čisté dáta ako <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">sales_data_clean.csv</span>,</li>
<li>uložte zamietnuté riadky ako <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">sales_data_rejected.csv</span>,</li>
<li>uložte validačný report ako <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">validation_report.csv</span>.</li>
</ul>
<div style="margin-top: 12px; background-color: #f9fafb; border-left: 4px solid #60a5fa; padding: 12px; border-radius: 4px;"> 💡 <strong>Pomôcka:</strong> Výsledok validácie nemusí byť iba jeden „opravený“ súbor.
V praxi je užitočné uchovať:
<ul style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.7; margin-top: 6px;">
<li>čisté dáta, ktoré môžu pokračovať ďalej,</li>
<li>zamietnuté záznamy na kontrolu,</li>
<li>súhrnný report s počtom chýb.</li>
</ul>
Na zápis CSV použite <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">to_csv(..., index=False)</span>.
</div>

In [17]:
OUTPUT_CLEAN = "sales_data_clean.csv"
OUTPUT_REJECTED = "sales_data_rejected.csv"
OUTPUT_REPORT = "validation_report.csv"

outputs_to_save = {
    OUTPUT_CLEAN: clean_final,
    OUTPUT_REJECTED: rejected_records,
    OUTPUT_REPORT: validation_report,
}

for file_name, data in outputs_to_save.items():
    try:
        data.to_csv(file_name, index=False)
    except PermissionError:
        print(f"CHYBA: do '{file_name}' sa nedá zapisovať nie je súbor otvorený napr. v Exceli?")
        raise
    print(f"Uložené: {file_name} riadky: {data.shape[0]}, stĺpce: {data.shape[1]}")

Uložené: sales_data_clean.csv riadky: 119, stĺpce: 10
Uložené: sales_data_rejected.csv riadky: 81, stĺpce: 20
Uložené: validation_report.csv riadky: 12, stĺpce: 4

<h2
  style="margin: 24px 0 16px; font-size: 20px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 6px;">
  💻 Úloha 14 – Kontrola vytvorených výstupov
</h2>

<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">
  Po uložení výsledkov validácie znovu načítajte vytvorené súbory a skontrolujte,
  či obsahujú očakávané údaje.
</p>

<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">
  Načítajte a zobrazte prvých niekoľko riadkov súborov:
</p>

<ul style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.7; margin-top: 6px;">
  <li><span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">sales_data_clean.csv</span>,</li>
  <li><span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">sales_data_rejected.csv</span>,</li>
  <li><span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">validation_report.csv</span>.</li>
</ul>

<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">
  Pri každom výstupe skontrolujte:
</p>

<ul style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.7; margin-top: 6px;">
  <li>počet riadkov a stĺpcov,</li>
  <li>názvy stĺpcov,</li>
  <li>dátové typy,</li>
  <li>prvých 5 riadkov.</li>
</ul>

In [18]:
read_options = {
    OUTPUT_CLEAN: {
        "dtype": {
            "OrderID": "string", "CustomerName": "string", "PhoneNumber": "string",
            "Region": "category", "Product": "category",
        },
        "parse_dates": ["OrderDate", "DeliveryDate"],
    },
    OUTPUT_REJECTED: {"dtype": str},   # zamietnuté dáta necháme ako text, tak ako prišli
    OUTPUT_REPORT: {},
}

loaded = {}
for file_name, options in read_options.items():
    data = load_csv(file_name, **options)   # rovnaké bezpečné načítanie ako v úlohe 1
    loaded[file_name] = data
    print("=" * 70)
    print(file_name)
    print("Počet riadkov a stĺpcov:", data.shape)
    print("Stĺpce:", list(data.columns))
    print("Dátové typy:")
    print(data.dtypes.to_string())
    display(data.head())

n_clean = len(loaded[OUTPUT_CLEAN])
n_rejected = len(loaded[OUTPUT_REJECTED])
print("=" * 70)
print(f"Čisté + zamietnuté = {n_clean} + {n_rejected} = {n_clean + n_rejected} (vstup: {len(df)} riadkov)")
assert n_clean + n_rejected == len(df), "Počet riadkov vo výstupoch nesedí so vstupom!"
assert loaded[OUTPUT_CLEAN]["OrderID"].is_unique, "V čistých dátach sú duplicitné OrderID!"
assert set(loaded[OUTPUT_REPORT]["validation_rule"]) == set(flags.columns), "Report nemá všetky pravidlá!"
print("Výstupy sú úplné a konzistentné so vstupom.")

======================================================================
sales_data_clean.csv
Počet riadkov a stĺpcov: (119, 10)
Stĺpce: ['OrderID', 'CustomerName', 'Region', 'Product', 'Quantity', 'SalesAmount', 'Discount', 'OrderDate', 'DeliveryDate', 'PhoneNumber']
Dátové typy:
OrderID         string[python]
CustomerName    string[python]
Region                category
Product               category
Quantity                 int64
SalesAmount            float64
Discount               float64
OrderDate       datetime64[ns]
DeliveryDate    datetime64[ns]
PhoneNumber     string[python]

,OrderID,CustomerName,Region,Product,Quantity,SalesAmount,Discount,OrderDate,DeliveryDate,PhoneNumber
0,ORD1015,Charlie Lee,West,Phone,7,840.00,20.0,2025-01-16,2025-01-19,<NA>
1,ORD1030,Alice Johnson,West,Phone,6,1805.15,15.0,2025-01-31,2025-02-01,<NA>
2,ORD1128,Bob Smith,South,Laptop,9,3083.23,5.0,2025-05-09,2025-05-11,<NA>
3,ORD1170,Lola Ade,North,Accessory,1,1380.89,10.0,2025-06-20,2025-06-22,<NA>
4,ORD1174,Alice Johnson,South,Unknown,9,3710.03,15.0,2025-06-24,2025-07-02,12025550178

======================================================================
sales_data_rejected.csv
Počet riadkov a stĺpcov: (81, 20)
Stĺpce: ['OrderID', 'CustomerName', 'Region', 'Product', 'Quantity', 'SalesAmount', 'Discount', 'OrderDate', 'DeliveryDate', 'PhoneNumber', 'OrderDate_clean', 'DeliveryDate_clean', 'Region_clean', 'Product_clean', 'Quantity_clean', 'SalesAmount_clean', 'Discount_clean', 'PhoneNumber_clean', 'rejection_reason', 'warnings']
Dátové typy:
OrderID               object
CustomerName          object
Region                object
Product               object
Quantity              object
SalesAmount           object
Discount              object
OrderDate             object
DeliveryDate          object
PhoneNumber           object
OrderDate_clean       object
DeliveryDate_clean    object
Region_clean          object
Product_clean         object
Quantity_clean        object
SalesAmount_clean     object
Discount_clean        object
PhoneNumber_clean     object
rejection_reason      object
warnings              object

,OrderID,CustomerName,Region,Product,Quantity,SalesAmount,Discount,OrderDate,DeliveryDate,PhoneNumber,OrderDate_clean,DeliveryDate_clean,Region_clean,Product_clean,Quantity_clean,SalesAmount_clean,Discount_clean,PhoneNumber_clean,rejection_reason,warnings
0,ORD1095,Bob Smith,South,Unknown,-1,2710.16,15,2025-04-06,2024-02-30,+2348012345678,2025-04-06,NaN,South,Unknown,-1.0,2710.16,15.0,2348012345678,"invalid_quantity, invalid_delivery_date",NaN
1,ORD1158,Ibrahim Musa,North,phone,0,NaN,5,2025-06-08,2025-06-21,+1-202-555-0178,2025-06-08,2025-06-21,North,Phone,0.0,NaN,5.0,12025550178,"invalid_quantity, invalid_sales_amount",NaN
2,ORD1115,Rita Gomez,North,Unknown,-1,3876.36,10,2025-04-26,2025-05-04,+1-202-555-0178,2025-04-26,2025-05-04,North,Unknown,-1.0,3876.36,10.0,12025550178,invalid_quantity,NaN
3,ORD1069,Oluwaseun Adebayo,north,Tablet,3.5,2518.94,NaN,2025-03-11,2025-03-15,(202) 555-0189,2025-03-11,2025-03-15,North,Tablet,3.5,2518.94,NaN,2025550189,"invalid_quantity, invalid_discount",NaN
4,ORD1045,Ibrahim Musa,Souht,phone,2,??,15,2025-02-15,2025-02-19,12345,2025-02-15,2025-02-19,South,Phone,2.0,NaN,15.0,NaN,invalid_sales_amount,invalid_phone

======================================================================
validation_report.csv
Počet riadkov a stĺpcov: (12, 4)
Stĺpce: ['validation_rule', 'invalid_rows', 'invalid_pct', 'severity']
Dátové typy:
validation_rule     object
invalid_rows         int64
invalid_pct        float64
severity            object

      validation_rule  invalid_rows  invalid_pct  severity
0       invalid_phone            34         17.0   warning
1    invalid_quantity            24         12.0  critical
2  duplicate_order_id            22         11.0  critical
3    missing_customer            22         11.0   warning
4    invalid_discount            20         10.0  critical

======================================================================
Čisté + zamietnuté = 119 + 81 = 200 (vstup: 200 riadkov)
Výstupy sú úplné a konzistentné so vstupom.

<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">
Po tejto časti by ste nemali validáciu dát vnímať iba ako kontrolu chýbajúcich hodnôt alebo jednoduché odstránenie chybných riadkov.
</p>

<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">
Mali by ste vedieť:
</p>

<ul style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.7; margin-top: 6px;">
<li>bezpečne načítať vstupný súbor a vhodne reagovať na chyby pri jeho spracovaní,</li>
<li>skontrolovať štruktúru datasetu, dátové typy a chýbajúce hodnoty,</li>
<li>overiť, či vstup obsahuje všetky očakávané stĺpce,</li>
<li>identifikovať nesprávne formáty, neplatné hodnoty a duplicity,</li>
<li>zjednotiť nekonzistentné textové a kategóriové hodnoty,</li>
<li>bezpečne konvertovať číselné a dátumové údaje,</li>
<li>kontrolovať nielen formát údajov, ale aj ich logickú správnosť,</li>
<li>vytvoriť validačné pravidlá a prehľad nájdených problémov,</li>
<li>oddeliť validné záznamy od záznamov, ktoré vyžadujú ďalšiu kontrolu,</li>
<li>opätovne overiť vyčistené dáta pred ich ďalším spracovaním alebo uložením.</li>
</ul>

<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">
Pri práci s dátami nie je cieľom každú chybu automaticky opraviť alebo nahradiť nulou. Najskôr je potrebné problém identifikovať, pochopiť jeho význam a až potom rozhodnúť, či je možné hodnotu bezpečne opraviť, označiť ako neplatnú alebo celý záznam oddeliť na ďalšiu kontrolu.
</p>

<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">
Takýto postup je dôležitý najmä pri automatizovanom spracovaní dát, kde sa rovnaká validácia môže opakovane vykonávať nad novými vstupnými súbormi ešte predtým, než sa dáta dostanú do ďalších častí dátovej pipeline.
</p>

<h2
  style="margin: 24px 0 16px; font-size: 20px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 6px;">
  📘 Kontrola Git repozitára po 5. týždni
</h2>

<p style="color: #1f2937; line-height: 1.65;">
  Po dokončení všetkých úloh z 5. týždňa skontrolujte, či máte vo svojom Git
  repozitári vytvorenú samostatnú vetvu
  <span
    style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">week-05</span>
  a či sa v nej nachádzajú všetky notebooky, vstupné datasety a výstupné súbory
  vytvorené počas cvičenia.
</p>

<p style="color: #1f2937; line-height: 1.65;">
  Obsah vetvy
  <span
    style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">week-05</span>
  by mal mať približne nasledujúcu štruktúru:
</p>

<pre
  style="background: #f9fafb; color: #111827; padding: 16px; border-radius: 8px; overflow: auto; font-size: 14px; line-height: 1.7; font-family: ui-monospace, SFMono-Regular, Menlo, monospace;">week-05
│
├── file_handling.ipynb
├── error_handling.ipynb
│
├── high_salary.csv
├── it_employees.csv
├── west_region_sales.xlsx
│
├── sales_report.parquet
├── sales_report2.parquet
├── yellow_tripdata_2024-01.parquet
│
├── sales_data_dirty.csv
├── sales_data_clean.csv
├── sales_data_rejected.csv
└── validation_report.csv</pre>

<p style="color: #1f2937; line-height: 1.65;">
  V repozitári ponechajte nielen samotné notebooky, ale aj vstupné a výstupné
  súbory, s ktorými ste počas cvičenia pracovali. Vďaka tomu bude možné neskôr
  skontrolovať jednotlivé kroky spracovania dát a nadviazať na ne v ďalších
  častiach dátovej pipeline.
</p>

<div
  style="margin-top: 12px; background-color: #fff7ed; border-left: 4px solid #f59e0b; padding: 12px; border-radius: 4px;">
  ⚠️ <strong>Kontrola GitHubu:</strong> Skontrolujte, či sa všetky uvedené súbory
  nachádzajú aj vo vzdialenom repozitári na GitHube. Ak ich vidíte iba lokálne
  vo VS Code, zmeny ešte neboli úspešne odoslané pomocou
  <strong>commit</strong> a <strong>push</strong>.
</div>